### ISSUE TITLE
The crashes API fails when there's no REDASH_API_KEY

### ISSUE THREAD

**Issue by armenzg** [mozilla/firefox-health-backend#18]
If we load http://localhost:3000/api/crashes without specifying a REDASH_API_KEY we get a 500 error and this message in the backend.

In order to improve local development we should fix this or create a procedure to procure a local development key.

>   AssertionError [ERR_ASSERTION]: process.env.REDASH_API_KEY missing
>       at /Users/armenzg/repos/health/backend/src/fetch/redash.js:5:10
>       at new Promise (<anonymous>)
>       at fetchRedash (/Users/armenzg/repos/health/backend/src/fetch/redash.js:4:16)
>       at Object.<anonymous> (/Users/armenzg/repos/health/backend/src/crashes.js:51:23)
>       at new Promise (<anonymous>)
>       at module.exports../src/crashes.js.router.get.ctx (/Users/armenzg/repos/health/backend/src/crashes.js:50:13)
>       at dispatch (/Users/armenzg/repos/health/backend/node_modules/koa-compose/index.js:44:32)
>       at next (/Users/armenzg/repos/health/backend/node_modules/koa-compose/index.js:45:18)
>       at /Users/armenzg/repos/health/backend/node_modules/koa-router/lib/router.js:345:16
>       at dispatch (/Users/armenzg/repos/health/backend/node_modules/koa-compose/index.js:44:32)

**Comment by armenzg** [comment]
This code was removed sometime in the last year.

**Comment by armenzg** [comment]
I think this got fixed in issue #23
