### ISSUE TITLE
Improve GET /release test

### ISSUE THREAD

**Issue by armenzg** [mozilla/firefox-health-backend#37]
Failing on Travis.
```node
  /release
    GET /release/
Unmatched get to https://product-details.mozilla.org/1.0/firefox_versions.json
  Error: No fallback response defined for get to https://product-details.mozilla.org/1.0/firefox_versions.json
      at Object.FetchMock.executeRouter (/home/travis/build/mozilla/firefox-health-backend/node_modules/fetch-mock/src/lib/fetch-handler.js:55:9)
      at Object.FetchMock.fetchHandler (/home/travis/build/mozilla/firefox-health-backend/node_modules/fetch-mock/src/lib/fetch-handler.js:7:22)
      at /home/travis/build/mozilla/firefox-health-backend/src/fetch/text.js:31:26
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
      1) should return 200
```

**Comment by armenzg** [comment]
We removed this code in the last year.
