### ISSUE TITLE
getChromePopular fails often

### ISSUE THREAD

**Issue by armenzg** [mozilla/firefox-health-backend#7]
It turns many Travis runs red.

```
  1) getChromePopular
       should return an array:
     FetchError: request to https://bugzilla.mozilla.org/rest/bug?id=723959%2C995651%2C1158032%2C1124223%2C1177910%2C1175958%2C1352643%2C1291894%2C1389458%2C1353636%2C1425291%2C1256575%2C1380881%2C1434007%2C746142%2C1402892%2C1413999%2C1425685%2C1362154%2C1272409%2C1361876%2C1062849%2C951793%2C1270146%2C1019116%2C567283%2C1361856%2C1225665%2C1286097%2C1240072%2C1312422%2C1357785%2C1343819%2C1109751%2C970802%2C709490%2C1319958%2C1338004%2C888177%2C1290958%2C1184036%2C1128959%2C1281769%2C1253706%2C976073%2C1011369%2C1063162%2C59109%2C1112032%2C1226042%2C886646%2C1264164%2C1298329%2C1287706%2C1285685%2C911477%2C1265318%2C1154309%2C1057180%2C1299483%2C1150081%2C1128959%2C1152918%2C366559%2C1244768%2C1245000%2C1222516%2C920633%2C1138384%2C1208296%2C1069063%2C1190641%2C1155730%2C935216%2C1135160%2Cnew.target%2C1153322%2C1139297%2C952643%2C903441%2C936340%2C1245000%2C870022%2C819900%2C840640%2C795567%2C940842%2C1064737%2C1245000%2C970600%2C1028497%2C887538%2C938686%2C600919%2C861266%2C629350%2C704320%2C1057180%2C677638%2C1089255&include_fields=id%2Ccf_tracking_firefox_relnote%2Ctarget_milestone%2Cassigned_to%2Cflags%2Ccf_status_firefox50%2Ccf_status_firefox51%2Ccf_status_firefox52%2Ccf_status_firefox53%2Ccf_status_firefox54%2Ccf_status_firefox55%2Ccf_status_firefox56%2Ccf_status_firefox57%2Ccf_status_firefox58%2Ccf_status_firefox59%2Ccf_status_firefox60 failed, reason: socket hang up
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:387:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by dylanwh** [comment]
How often is that being called? You might be getting hit by the rate limiting.

**Comment by armenzg** [comment]
Travis only runs when I commit code to this repositories in one of its branches.
Not often. At most few times in a short span of minutes (e.g. I push, ammend and push -f again)

**Comment by armenzg** [comment]
This code was removed sometime in the last year.
